# Generated by ChatGPT

import os
import zipfile
import urllib.request
from collections import Counter
import string

ZIP_URL = "https://github.com/jlowin/fastmcp/archive/refs/heads/main.zip"
ZIP_NAME = "fastmcp-main.zip"

# Global variable to store documents
_documents = None


def _download_zip():
    """Download ZIP if not already present."""
    if os.path.exists(ZIP_NAME):
        return
    print(f"Downloading {ZIP_NAME}...")
    urllib.request.urlretrieve(ZIP_URL, ZIP_NAME)
    print("Download complete.")


def _load_documents():
    """Read all .md and .mdx files from ZIP and return a list of dicts."""
    docs = []
    with zipfile.ZipFile(ZIP_NAME, "r") as z:
        for name in z.namelist():
            if not (name.endswith(".md") or name.endswith(".mdx")):
                continue
            parts = name.split("/", 1)
            if len(parts) < 2:
                continue
            clean_name = parts[1]
            with z.open(name) as f:
                try:
                    content = f.read().decode("utf-8")
                except:
                    continue
            docs.append({"filename": clean_name, "content": content})
    return docs


def _ensure_documents_loaded():
    """Ensure documents are loaded into the global variable."""
    global _documents
    if _documents is None:
        _download_zip()
        _documents = _load_documents()


def search(query, limit=5):
    """
    Search the preloaded documents for a query string.
    Returns a list of top results (each is a dict with 'filename' and 'content').
    """
    _ensure_documents_loaded()
    query_words = query.lower().split()
    scored = []
    for doc in _documents:
        content = (
            doc["content"].lower().translate(str.maketrans("", "", string.punctuation))
        )
        words = content.split()
        counter = Counter(words)
        score = sum(counter.get(w, 0) for w in query_words)
        if score > 0:
            scored.append((score, doc))
    scored.sort(key=lambda x: (-x[0], x[1]["filename"]))  # sort by score, then filename
    return [d for score, d in scored[:limit]]


# Example usage
if __name__ == "__main__":
    while True:
        q = input("Enter your query (or 'exit' to quit): ")
        if q.lower() == "exit":
            break
        results = search(q)
        if not results:
            print("No results found.")
        for i, doc in enumerate(results, 1):
            print(f"\nResult {i}")
            print("Filename:", doc["filename"])
            print("Preview:", doc["content"][:200].replace("\n", " "), "...")
